import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // eslint-plugin-react auto-detects the React version by reading the
    // filesystem through `context.getFilename()`, which ESLint 10 removed — so
    // detection throws while merely loading a rule. Naming the version skips
    // detection entirely.
    settings: { react: { version: "19.2" } },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `convex codegen`.
    "convex/_generated/**",
  ]),
])

export default eslintConfig
